# Generated by Django 3.2.7 on 2021-11-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_id', models.CharField(max_length=20)),
                ('prize_cname', models.CharField(max_length=20)),
                ('prize_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ssn', models.CharField(max_length=3)),
                ('prize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.prize')),
            ],
        ),
    ]
