# Generated by Django 4.2.1 on 2023-05-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='tall',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='people',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
